sudo: false
  language: python
  python:
    - "2.7"
  install:
    - pip install -r requirements.txt
    - pip install flake8==3.5.0 pylint==1.8.2
 script:
   - flake8 esphomeyaml
   - pylint esphomeyaml
